services:
  nextjs:
    build: ./
    container_name: nextjs
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextjs

